/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'backend',
        'frontend',
        'auth',
        'users',
        'roles',
        'branches',
        'employees',
        'customers',
        'accounts',
        'transactions',
        'loans',
        'ledger',
        'reports',
        'audit',
        'notifications',
        'settings',
        'common',
        'config',
        'docker',
        'docs',
        'ci',
        'deps',
        'release',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'header-max-length': [2, 'always', 100],
  },
};
